apiVersion: v1
data:
  google-service-acc-key.json: |
      type=service_account
      project_id=<PROJECTID>
      private_key_id=xxxxxxxx
      private_key=-----BEGINPRIVATEKEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASC
      
      -----END PRIVATE KEY-----
      client_email=pubsub-app@xxxx.iam.gserviceaccount.com
      client_id=xxxxx
      auth_uri=https://accounts.google.com/o/oauth2/auth
      token_uri=https://oauth2.googleapis.com/token
      auth_provider_x509_cert_url=https://www.googleapis.com/oauth2/v1/certs
      client_x509_cert_url=https://www.googleapis.com/robot/v1/metadata/x509/iam.gserviceaccount.com
kind: ConfigMap
metadata:
  name: gcp-configmap
  namespace: kafka