apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  kafka.brokers: my-cluster-kafka-bootstrap:9092
  application.properties: |
    camel.component.kafka.brokers=my-cluster-kafka-bootstrap:9092